FROM node:latest
RUN apk add --no-cache --update make gcc g++ python libgcc libstdc++
RUN npm install -g node-gyp

WORKDIR /app
ADD . /app
RUN npm install
ENV PORT = 80
EXPOSE 80
CMD [ "npm","start" ]